### ISSUE TITLE
SMS send session error at intervals 

### ISSUE THREAD

**Issue by bajil2203** [zinen/node-red-contrib-huawei-router#13]
HI, I am using Huawei 8372 wiggle to send out SMS from a node. The SMS send works okay if trigger is not frequent. But with repeated triggers, pops errors as 125003: Unknown or 125002 : Session. To overcome, used a simple queue to hold the messages and triggers one by one with  a delay 10 sec, to 1 minute, The pattern is still the same that after every 2 SMS send successful, there will be 2 errors and following triggers send the SMS for the next 2. Followed by 2 error again. The pattern is same that session error pops out every 2 SMS. Any inputs to resolve this or suggest a workaround will be helpful. Please revert. Thanks
![Nodered_SMS_error](https://user-images.githubusercontent.com/110051665/181062968-8cc328cd-b02a-43ae-a289-559e991f3d3e.jpg).
The issue looks similar to the other post for reading SMS.

**Comment by bajil2203** [comment]
Any tips or  a workaround will be helpful. Please advise where this session time can be changed or the current value. Appreciate a reply.

**Comment by zinen** [comment]
Hmm. This could be that the session time of your router does not match the one I tested with. Current session time it clocked at around [300 seconds ](https://github.com/zinen/node-red-contrib-huawei-router/blob/07906b1a92568e01886ed926547979ae163e0f7f/huawei-router/huawei-router.js#L15). And I did not expose this as a setting in router config.

But that should be very possible. I'll require a bit of time to test it though. In the mean time. Could you find the exact limit of your session?

Also what versions are you running? Node. Js, node-red and this node.

**Comment by grawsom** [comment]
@bajil2203 
@zinen 
I had the same problem when checking for new sms', what I did was mad a new flow where I use the API directly. see [here](https://github.com/zinen/node-red-contrib-huawei-router/issues/11#issuecomment-1126942987)

I have now made a sendSms  - you can try that out until node works better.

```
[{"id":"e90e5caf362b3b81","type":"inject","z":"b1c0d59a0b7da425","name":"","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"12345678","payload":"Test test","payloadType":"str","x":170,"y":860,"wires":[["9ee0d80b2a14524c"]]},{"id":"9ee0d80b2a14524c","type":"function","z":"b1c0d59a0b7da425","name":"API - sendSms","func":"var phoneNumber = msg.topic;\nvar message = msg.payload;\n\nlet connection\n//async function sendSms() {\n    try {\n        connection = new huaweiLteApi.Connection('http://admin:admin@192.168.8.1/')\n        await connection.ready\n        const result = await new huaweiLteApi.Sms(connection).sendSms(phoneNumber, message)\n        msg.payload = result\n        \n        console.log('sendSSms result =', result)\n    } catch (error) {\n        console.error('Ended in error:')\n        console.error(error)\n    } finally {\n        const user = new huaweiLteApi.User(connection)\n        // finallyCode - Code block to be executed regardless of the try result\n        const resultLogout = await user.logout()\n        console.log('result from logout=', resultLogout)\n        connection = null\n    }\n//}sendSms()\nreturn msg;\n","outputs":1,"noerr":0,"initialize":"","finalize":"","libs":[{"var":"huaweiLteApi","module":"huawei-lte-api"}],"x":400,"y":860,"wires":[["57e9f8ca5d86fa46"]]}]
```

**Comment by zinen** [comment]
Untested version but with the session timeout accessible as a config. Please try it and give any feedback.

Install node directly as found on github. This does require you the reach the terminal and can not be done from node-red interface.
```
npm install https://github.com/zinen/node-red-contrib-huawei-router.git#varible-session-timeout
```

**Comment by bajil2203** [comment]
Thanks for the reply. Will test out and feedback on the test status.

Regards

**Comment by bajil2203** [comment]
Simulated Offline test looks good after changing the session time. However, couldn't find the timeout in the router configuration, but a random trial of 90 secs for now is good for the flow as now. will test out in the field shortly. Really appreciate the support

**Comment by bajil2203** [comment]
Hi, The node is not getting registered in newer npm ver 8.x, but in my PC which is running 6.14.15, is working fine. Please advise. thanks.

**Comment by zinen** [comment]
Bumped to version 1.2.2a aaf2dd9cca1739fca64d17867139e4b28b852b39 may fix this.

**Comment by zinen** [comment]
Variable session timeout added to main branch in version 1.3.0.
