### ISSUE TITLE
"125002: Session error"

### ISSUE THREAD

**Issue by HerrTuulik** [zinen/node-red-contrib-huawei-router#15]
Hello!

What does this error mean?
I have three instances of the huawei info node, Month statistics, Monitor Node, Traffic statistics.
Monitor node returns this error when called, the others seem to work fine.

I'm using huawei e5576-320

**Comment by HerrTuulik** [comment]
Didin't notice the post post below at first so i tried that. Timeout is 5 minutes or 300 seconds, which seems to be very close to the default 298 seconds. Set it to 300 but this error still occurs.

**Comment by zinen** [comment]
Yeah so the 298 seconds is my way of making sure that the 5 minutes timeout is respected minus 2 seconds as a safety measure. 
Question 1: Do you use the same server config for all your 3 nodes? 

![image](https://user-images.githubusercontent.com/9595798/214028426-12d81833-3cf7-4012-83c1-0dccaad4b638.png)

Using the same server config should make sure that they share the session and so not to hit the amount of session limit. Might be that they try is request data at the same time and the router cant handle this.  
Question 2: Are the nodes actives at the same time? If so try making them run one by one. I haven't implemented a queueing system as I haven't seen this problem you speak of. But I only run one node at a time.

Question 3: Also what version of this node are you using?

**Comment by HerrTuulik** [comment]
Yes, they all share the same config.
I'm on version 1.3.0
Some more info, maybe a clue:

- All three nodes are inside a subflow with an inject node calling all three, currently once every minute.
- the config ip and password are derived from environment variables. Ex: "${ip}","${passwd}. 

I'll try offsetting the injections and report back the results next time i get the chance.

**Comment by HerrTuulik** [comment]
Offsetting the injection times worked! Thank you for your advice.

**Comment by zinen** [comment]
This suggest that a queue system might be a good addition. I'll note that to the API owner or maybe try implementing this myself in this module. Thanks for testing

**Comment by zinen** [comment]
I raised issue#28 at https://github.com/Salamek/huawei-lte-api-ts/issues/28 to hear about this.

**Comment by zinen** [comment]
I had multiple request  noted for a version 2 update which was just released. Some included breaking changes but one of these was to implement a simple queuing feature as per this issue. 

The simple queue is now in place. @HerrTuulik feel free to test this out and tell me if it works for you.

**Comment by zinen** [comment]
No response. Closing issue
