### ISSUE TITLE
Problem Connecting to Huawei Router B593u-12

### ISSUE THREAD

**Issue by jgichimu** [zinen/node-red-contrib-huawei-router#16]
Experiencing below error .Running Nodejs 19.2 and npm 9.3 on windows.

Unexpected close tag
Line: 23
Column: 7
Char: >

![Huawei Node 1](https://user-images.githubusercontent.com/50748382/213886402-1d321575-a18c-46bb-9648-f78c4611f576.PNG)
![Huawei Node 2](https://user-images.githubusercontent.com/50748382/213886404-08d8c332-1633-4c56-82cb-e417408e032d.PNG)

**Comment by zinen** [comment]
Looks the an error parsing the incoming response back from the router containing html code. This is an error from the [huawei-lte-api](https://github.com/Salamek/huawei-lte-api-ts) module and so I can't fix this. On the linked page I see router `B593s-22` mentioned being incompatible, might be the same for your `B593u-12` router. It would be best if you post an issue on that page and do some test with the author to fix the problem. Their issue page is found here: https://github.com/Salamek/huawei-lte-api-ts/issues
