### ISSUE TITLE
Huawei E5776s-32

### ISSUE THREAD

**Issue by Wirewrap** [zinen/node-red-contrib-huawei-router#9]
I am trying to use a Huawei E5776s-32. 4G router.
There is a html page served from the router that can send and receive SMS successfully.
 There are lots of references in the js files on the html page to API like 
               saveAjaxData("api/sms/send-sms", submitData, function($xml)
so there is an API, unfortunately I cannot understand the code.
Would be nice to log what the browser sends to the router, but I don't know how.

Current versions: NodeRed v2.1.3  node-red-contrib-huawei-router 1.1.1

I installed the flow from "Problem with SMS node #8"

The debug printout says:

1/8/2022, 8:28:53 PMnode: 83abfca9ac3e306c
msg : Object
object
_msgid: "985eb045a6690534"
payload: 1641670133237
topic: ""
error: object
message: "100002: No support"
source: object
id: "d4fff9bea78e8e27"
type: "huawei-lanhosts"
name: undefined
count: 1

Is there any hope to get this router running under node red?
I would love to do some debugging if you care to help me.

**Comment by grawsom** [comment]
First I think that you need to address this to [@Salamek](https://github.com/Salamek/huawei-lte-api) who makes the API that is used behind this package, maybe your device is not supported yet(can't see it refrenced on page), or test that API out directly to see if it works.

**Comment by Wirewrap** [comment]
OK, I will give it a try myself in Python. Never coded Python before.
I found the program "Fiddler" that shows HTTP requests and responses so I will simply parrot what the builtin server page does.
So far I can login to the router and show login status.
